### ISSUE TITLE
Cgroup adding blank columns

### ISSUE THREAD

**Issue by jlombard314159** [gforge/htmlTable#10]
Why are spacer cells added between column groups? Is there a way to assign column groups without spacer cells? For the application I'm using your package for when those blank cells are added the CSS properties that I apply externally really do not jive well with the blank spaces in there. I tried to modify the htmlTable function on my local machine to see if I could provide a solution but I was not able to solve the issue.

Thanks! (Code is below: lines 527-529. At least that's where I think those blank columns are being added) 

```
# With multiple rows in cgroup we need to keep track of
 # how many spacer cells occur between the groups
  cgroup_spacer_cells <- rep(0, times=(ncol(x)-1))

```

**Comment by gforge** [comment]
The empty cell is needed for avoiding the underline not to merge between adjacent cgroups. If you want to add an option that removes this take a look at these to sections:
- https://github.com/gforge/htmlTable/blob/master/R/htmlTable_helpers.R#L291
- https://github.com/gforge/htmlTable/blob/master/R/htmlTable_helpers.R#L551-L568
