### ISSUE TITLE
Date classes changed to numeric

### ISSUE THREAD

**Issue by iembry-USGS** [gforge/htmlTable#14]
I have some tables that have the Date class, but have been changed to numeric with `htmlTable`.

Is it possible to retain the date/time classes (POSIXct, Date, chron, etc.) when the htmlTable is printed?

Thank you.

Irucka Embry

**Comment by gforge** [comment]
Thanks for the report. See if the new dev version fixes this.

**Comment by iembry-USGS** [comment]
Hi, I downloaded and use the new dev version, but it does not fix the issue.

Thank you.

**Comment by gforge** [comment]
Odd, could you sent me an example that replicates this issue?

**Comment by lemna** [comment]
``` r
require(lubridate)
require(htmlTable)
require(chron)
df_dates <- data.frame(ID = 1:3,
                       contact_Date = c(today(),
                                        today() - 1,
                                        today() - 2))

df_dates$contact_posix <- strptime(as.POSIXct(df_dates$contact_Date),
                                     format = "%Y-%m-%d")
df_dates$contact_chron <- chron(as.character(df_dates$contact_Date),
                                format = "Y-m-d",
                                out.format = "Y-m-d")
df_dates
htmlTable(df_dates)
```

Contact_chron is displayed incorrectly when using the develop branch.

**Comment by gforge** [comment]
Excellent.Thanks @lemna!

**Comment by iembry-USGS** [comment]
@gforge  - Thank you for this fix.
