### ISSUE TITLE
txtRound digits when 1 < length(digits) < ncol(x)

### ISSUE THREAD

**Issue by lemna** [gforge/htmlTable#16]
When you specify a vector for the `digits` argument with a length smaller than the number of columns, a warning is thrown instead of an error. Compare:

``` r
test_mx <- matrix(c(1, 1.11, 1.25,
2.50, 2.55, 2.45,
3.2313, 3, pi),
ncol = 3, byrow=TRUE)

# works as expected
txtRound(test_mx, digits = 1)
# throws an error, as expected
txtRound(test_mx, digits = rep(1, 4))
# only throws a warning
txtRound(test_mx, digits = rep(1, 2))
```

**Comment by gforge** [comment]
Awesome. Thanks for the fix and the tests. 

I recommend though that you work with the dev-branch next time. I usually have everything in the dev-branch between CRAN-submits.
