### ISSUE TITLE
Table pagination

### ISSUE THREAD

**Issue by zeehio** [gforge/htmlTable#20]
Hi,

I was wondering if it is currently possible to have the HTML table paginated... Showing for instance 10 rows and a previous/next page button.

I cannot find the option and it is a handy feature for long tables...

Thanks and sorry if I have missed it!

**Comment by gforge** [comment]
Sounds like a neat feature but its rather complicated to implement and requires advanced JavaScript coding. There is the `htmlTable::interactiveTable` that has some JavaScript associated with it that could be extended with more features. It is probably about 40-80 hour of coding though and I don't have the time resources available for this but anyone that wants is welcome to add this functionality to the `interactiveTable`

**Comment by zeehio** [comment]
I have a solution that uses htmlwidgets and jquery.

Would you mind depending on the htmlwidgets package for pagination?

I will submit a PR once it's finished. In case you don't like it I may use it in condformat anyway :+1:

**Comment by gforge** [comment]
Sounds awesome - go for it :-)

BTW - just had to update package to version 1.8 due to CRAN-errors.

**Comment by zeehio** [comment]
Feel free to review and merge whenever it is good for you :+1:
