### ISSUE TITLE
Specify text-align in css.cell?

### ISSUE THREAD

**Issue by zeehio** [gforge/htmlTable#22]
For some reason the `align` parameter in the htmlTable function makes it impossible to specify a `text-align` in the `css.cell` matrix. See the example and the result.

```r
library(htmlTable)
data <- data.frame(aaaaaa = letters[1:5],
                   baaaaa = LETTERS[1:5])
css_cell <- matrix('background-color: red;text-align: "right"', nrow = 5, ncol = 2)
htmlTable(data, css.cell = css_cell)

```

![imatge](https://cloud.githubusercontent.com/assets/75441/21784511/2d487f9e-d6bc-11e6-8868-4e37058a2699.png)

If this is the expected behaviour that is fine, but it was a bit surprising that all the css style attributes were working except this one :sweat_smile:

**Comment by gforge** [comment]
I think it's over-ridden by the align-argument. Not sure that specifying at this level makes sence...

**Comment by gforge** [comment]
Thanks!
