### ISSUE TITLE
parameter nsmall

### ISSUE THREAD

**Issue by glennmschultz** [gforge/htmlTable#23]
I have this code which produces a table with a warning.  It seems nsmall is passed to format
   htmlTable(txtInt(ATOMS_AGG, language = "en", html = TRUE, nsmall = 4),
             header = ATOMSHeader,
             rnames = FALSE,
             css.cell = rbind(rep(
               "font-size: 1em; padding-left: 1em; padding-right: 1em;", 
               times=ncol(ATOMS_AGG)))
             )

Warning messages:
1: In FUN(X[[i]], ...) :
  The function can only be served integers, '0.3495' is not an integer. There will be issues with decimals being lost if you don't add the nsmall parameter.

here is the dataframe
structure(list(Orig_Bal = 5284699, Curr_Balance = 1847112, Num_Loans = 16866197L, 
    Num_Pools = 184290L, Factor = 0.3495, GWac = 3.89, Age = 34, 
    Wam = 289, RScore = 487, DScore = 848, CPR_1M = 15.06, CPR_3M = 41.42, 
    CPR_6M = 64.87, ATOMS_MTDRTN = 0.0057), class = "data.frame", row.names = c(NA, 
-1L), .Names = c("Orig_Bal", "Curr_Balance", "Num_Loans", "Num_Pools", 
"Factor", "GWac", "Age", "Wam", "RScore", "DScore", "CPR_1M", 
"CPR_3M", "CPR_6M", "ATOMS_MTDRTN"))

**Comment by gforge** [comment]
Thanks, bug in that the ... weren't passed onto sapply in txtInt. Fixed in the dev-branch.
