### ISSUE TITLE
RStudio notebook - print.htmlTable fails to detect that it should return an asis_output

### ISSUE THREAD

**Issue by gforge** [gforge/htmlTable#26]
The new RStudio notebook allows inline tables but this requires that the function returns `knitr::asis_output` instead of using the viewer. Unfortunately it currently ignores interactive use of knit_print and it doesn't have any obvious ways for detecting when running within a notebook.

**Comment by zeehio** [comment]
This works for me. Based on `htmltools::HTML`
```
a <- htmlTable::htmlTable(iris)
attr(a, "html") <- TRUE
class(a) <- c("html", "htmlTable", "character")
a
```

**Comment by gforge** [comment]
Thanks! Fixed. Working on the CRAN submission
