### ISSUE TITLE
print.htmlTable ignores option to write to file as well as useViewer

### ISSUE THREAD

**Issue by jciconsult** [gforge/htmlTable#30]
With R 3.3.3 and all latest stuff, the print(object, type="HTML",file="myfile.html".useViewer=FALSE) prints the htlml object inline.,

**Comment by raredd** [comment]
Is that not [this open issue](https://github.com/gforge/htmlTable/issues/27)?

```
ht <- htmlTable::htmlTable(mtcars)
class(ht) <- 'htmlTable'
ht
```

as a work-around

**Comment by gforge** [comment]
Yes, its the same issue. I still haven't gotten any feedback from the RStudio team regarding how to approach this...
