### ISSUE TITLE
Conforming to tidyverse custom

### ISSUE THREAD

**Issue by smithjd** [gforge/htmlTable#31]
It would be nice if tableHTML conformed to the tidyverse custom of working with magrittr chaining.  So for example, it would be nice to say:
`df %>% tableHTML(rownames = FALSE)`
Instead of the current:
`df %>% tableHTML(., rownames = FALSE)`

(GREAT package, by he way!)

**Comment by gforge** [comment]
What is the tableHTML function?

**Comment by smithjd** [comment]
My apologies -- it's a function of https://github.com/LyzandeR/tableHTML/
