### ISSUE TITLE
total option for last column?

### ISSUE THREAD

**Issue by dannyparsons** [gforge/htmlTable#33]
Firstly, thanks for this great package, really like the functionality.

The `total` parameter in `htmlTable` is very handy for when I have a total final row. Is there an easy (or hard) way to do the same for the last column? Is it something that could be incorporated in the `total` parameter in future?

Thanks.

**Comment by gforge** [comment]
I'm a little hesitant on adding more options, the css.cell in vector format fill this function though. Have a look at the docs and use the same setting as `css.total = "border-top: 1px solid #BEBEBE; font-weight: 900;",` for the styling.

**Comment by dannyparsons** [comment]
Thanks for the reply, I can do it through `css.cell`.
