### ISSUE TITLE
txtRound for vectors issue

### ISSUE THREAD

**Issue by lemna** [gforge/htmlTable#34]
Hi Max,

`txtRound()` returns unexpected results for vectors:

```R
> txtRound(c(1, 2, 3, 4))
[1] "1" "2" "3" "4"
Warning message:
In if (is.na(x)) return(txt.NA) :
  the condition has length > 1 and only the first element will be used
> txtRound(c(1, 2, 3, NA))
Error in if (round(v, d) == 0) v <- 0 : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In if (is.na(x)) return(txt.NA) :
  the condition has length > 1 and only the first element will be used
> txtRound(c(NA, NA, NA, NA))
[1] ""
Warning message:
In if (is.na(x)) return(txt.NA) :
  the condition has length > 1 and only the first element will be used
```

The first case should not result in a warning; the second case should not fail; the third case should return a vector of length 4. My guess is that this is caused by line 218-219 in `txtRmt.R`. I can submit a patch later this week if you're interested.

with kind regards,
Peter

**Comment by gforge** [comment]
This seems to be fixed in the development version - could you verify and I'll update CRAN

**Comment by lemna** [comment]
Thanks Max!

Works as expected in develop  - this issue can be closed.

Peter.
