### ISSUE TITLE
txtRound numbers in scientific notation

### ISSUE THREAD

**Issue by danli-ds** [gforge/htmlTable#35]
When using txtRound to round numbers in scientific notation, txtRound would only extract the numeric value and ignore the e-notation. For example, both `txtRound('1.693213e2', digits = 3)` and  `txtRound('1.693213e-2', digits = 3)` return `"1.693"`.

**Comment by lemna** [comment]
Apart from that obvious error it is also inconsistent, depending on the type of `x`:
```
> txtRound('1.693213e2', digits = 3)
[1] "1.693"
> txtRound(1.693213e2, digits = 3)
[1] "169.321"
```
I had expected that if `x` is in scientific notation, it would retain the scientific notation. Something like:
```
> txtRound('1.693213e2', digits = 3)
[1] "1.693e2"
> txtRound(1.693213e2, digits = 3)
[1] "1.693e2"
```
The current behavior is not desirable, IMO:
```
> txtRound(1.6932121e10, digits = 3)
[1] "16932121000.000"
```
Any thoughts?

**Comment by gforge** [comment]
I rarely use scientific as many of my peers have forgotten the notation. It seems like a good extension though, should be trivial to add.

**Comment by gforge** [comment]
Ok, I've added suggested but there seems to be a limitation since the `deparse(substitute())` can't detect the format of the numeric input value. The autodetect now only works with strings, otherwise you need to use scientific = true.
