### ISSUE TITLE
Removing Show X Entries in Shiny

### ISSUE THREAD

**Issue by harveymj** [gforge/htmlTable#38]
Hello, 

I have been using htmlTables to display data for a Shiny application. I don't have that much information in the tables so I'm sized them to include all data. Is there a way to easily remove the "Show X Entries" at the top left of the table? 

Thank you

**Comment by gforge** [comment]
You could try making this line: https://github.com/gforge/htmlTable/blob/master/R/htmlTableWidget.R removed when all data is within the min span. If it works do a pull request and I'll try to have a look at it.

**Comment by harveymj** [comment]
Happy to take a look at this solution. 

Additionally, I have found the CSS tag for this item.
If you name the table `myTable` for example, it can be ID'd by using `#myTable_entries`

Changing CSS to 
```
#myTable_entries{
  visibility: hidden;
}
```
Hides the information. I'm happy with this solution, but I have not checked its functionality across different browsers.
