### ISSUE TITLE
Multi-level Row Groups

### ISSUE THREAD

**Issue by graggsd** [gforge/htmlTable#39]
Hi Max,

Do you foresee implementing nested row-grouping similar to what is available for columns?

BTW: thanks very much for creating this package. I had been on the lookout for something with this functionality, and this works great!

**Comment by gforge** [comment]
Thanks. I don't have any plans for this although I don't mind if anyone (hint) would care to add this feature. I unfortunately lack the time at the moment to do larger changes.

**Comment by graggsd** [comment]
Looking through the code, it seems that might be a formidable task. Time (and ability) permitting, I'd be interested in helping out with this in the future, unless someone else more capable than myself makes themselves available.

**Comment by gforge** [comment]
Yeah, since I don't have a need for it I don't feel that I can spend the time needed on it.

**Comment by graggsd** [comment]
I wanted to retract this suggestion (and also clean up the issues page). The combination of rnames, rgroup, and tspanner should be more than enough to organize a table, and it is likely that adding additional rgroups will serve to 1) Complicated the development process and 2) Reduce the readability of the output table.

**Comment by gforge** [comment]
Thanks, I agree.
