### ISSUE TITLE
htmlTable tidy data interface

### ISSUE THREAD

**Issue by graggsd** [gforge/htmlTable#42]
I thought it might be useful include an interface for the htmlTable function that would allow mapping columns from a data.frame to specific htmlTable parameters such as rnames, headers, tspanner, rgroups, etc similar to ggplot2. That said, I built a wrapper function to exactly this (albeit with standard evaluation and less compatibility with tbl_df's.)

I don't know if you see this as within the scope of the package, but so I built a small package to contain this wrapper function.

[tidyhTbl](https://github.com/graggsd/tidyhTbl)

**Comment by gforge** [comment]
Good work! Looks like a neat addition. If you want to you can add it directly to the package or I can add a reference to it in my docs. I would call it `tidyTable` or possibly `tidyHtmlTable`; mixing camelCase with underscores is less desirable (although I'm pretty sure my naming conventions are not perfect in my packages...). Create a pull request with either a doc-reference or the function and I'll add it to the next release.

**Comment by gforge** [comment]
In 1.11.0 :-) Thanks!
