### ISSUE TITLE
htmlTable 1.11 requires an additional 20 meg of dependencies

### ISSUE THREAD

**Issue by jonathon-love** [gforge/htmlTable#47]
hi,

the latest `htmlTable` adds a dependency (import) on `tidyr`, which results in an additional 20 meg of dependencies requiring to be installed. this in turn has a non-trivial impact on the packages which in turn depend on `htmlTable`. for example, `Hmisc` imports `htmlTable`, and `Hmisc` is imported by [a lot of packages](http://cran.r-project.org/package=Hmisc), so this change has far reaching consequences.

i myself am coming from `gamlj` imports `lmerTest` imports `Hmisc` imports `htmlTable` imports `tidyr`.

is it feasible for `htmlTable` to be done in such a way that `tidyr` is a suggests rather than an import?

with thanks, and thanks for all your work

**Comment by graggsd** [comment]
Ah...that would be my fault with the addition of `tidyHtmlTable`.

I agree. This can be fixed by adding `tidyr` to `suggests`  and incorporating some code similar to the following into `tidyHtmlTable`

```
# You need the suggested package for this function    
my_fun <- function(a, b) {
  if (!requireNamespace("pkg", quietly = TRUE)) {
    stop("Pkg needed for this function to work. Please install it.",
      call. = FALSE)
  }
}
```

**Comment by gforge** [comment]
It think I solved it but there are CRAN-check issues, do you have time for adding a fix? 

From `devtools::check(args = c('--as-cran'))`

```
checking R code for possible problems ... NOTE
add_col_idx: no visible global function definition for ‘left_join’
add_row_idx: no visible global function definition for ‘left_join’
argument_checker: no visible global function definition for
  ‘is.grouped_df’
check_uniqueness: no visible global function definition for ‘select’
get_col_tbl: no visible global function definition for ‘select’
get_col_tbl: no visible global function definition for ‘arrange_at’
get_col_tbl: no visible global function definition for ‘mutate_if’
get_row_tbl: no visible global function definition for ‘select’
... 10 lines ...
  ‘spread’
tidyHtmlTable.data.frame: no visible global function definition for
  ‘pull’
tidyHtmlTable.data.frame: no visible global function definition for
  ‘slice’
Undefined global functions or variables:
  arrange_at filter is.grouped_df left_join mutate_at mutate_if pull
  select slice spread
Consider adding
  importFrom("stats", "filter")
to your NAMESPACE file.
```

**Comment by graggsd** [comment]
Hey, sorry. It's finals week right now. Do you mind giving me a couple of days? I can get to it as soon as I square away my last assignments.

**Comment by gforge** [comment]
No worries, good luck with the exams (can't say I miss them...)

**Comment by gforge** [comment]
New version submitted to CRAN. 

Happy holidays!
