### ISSUE TITLE
Issue with vector argument in `css.cell`

### ISSUE THREAD

**Issue by MrDAndersen** [gforge/htmlTable#55]
I was trying to figure a way to apply classes to individual rows. I was testing the approach based on the statement in the documentation that 
>If `css.cell` is a vector, it’s assumed that the styles should be repeated throughout the columns (that is, each element in `css.cell` specify the style for the whole row of ’x’).

However, when I run the following
```htmlTable(mtcars, rnames = FALSE, css.cell = paste0("row-class-", mtcars$cyl))```
I get the following error
``` 
Error in prPrepareCss(x, css = css.cell, rnames = rnames, header = header) : 
  The length of your css.cell vector '32' does not correspond to the column length '11' (there are no rownames)
```

What am I missing?

**Comment by lemna** [comment]
`css.cell` currently works by column, not by row - there seems to be a mismatch of code and documentation. Try this as a workaround:
```R
css.cell <- matrix(rep(paste0("row-class-", mtcars$cyl), ncol(mtcars)), ncol = ncol(mtcars))
htmlTable(mtcars, rnames = FALSE, css.cell = css.cell)
```

This is caused by lines 833-851 in htmlTable_helpers.R. @gforge, do you want the code or the documentation to be changed?
