### ISSUE TITLE
Bug with '$'-sign rendering?

### ISSUE THREAD

**Issue by gdemin** [gforge/htmlTable#57]
Hi,
First of all, thank you for great package.
I found strange behavior when I have a dollar sign in some cells of data.frame. When I knit such data.frame with htmlTable I get broken html. Note that this bug arises only when knitting. Rendering the same table in the RStudio viewer/RNotebook gives absolutely correct result.
![html_table_rendering](https://user-images.githubusercontent.com/3617375/38762583-08bfe31c-3f96-11e8-9214-d35c7731691d.PNG)
Code for reproducing:
```
---
title: "Untitled"
date: '14 april 2018 г '
output: html_document
---

```{r }
library(htmlTable)

## incorrect rendering
my_df = data.frame(
                row_labels = c("!", "!=", "$", "$<-", "%in%", "$", "(", "*"), 
                a1 = 1:8,
                a2 = 11:18,
                stringsAsFactors = FALSE)
htmlTable(my_df, escape.html = TRUE)
htmlTable(my_df, escape.html = FALSE)

## correct rendering after removing some dollar signs
my_df = data.frame(
                row_labels = c("!", "!=", "", "<-", "%in%", "$", "(", "*"), 
                a1 = 1:8,
                a2 = 11:18,
                stringsAsFactors = FALSE)
htmlTable(my_df, escape.html = TRUE)
htmlTable(my_df, escape.html = FALSE)

```

Session info:
```
## R version 3.4.3 (2017-11-30)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 16299)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251   
## [3] LC_MONETARY=Russian_Russia.1251 LC_NUMERIC=C                   
## [5] LC_TIME=Russian_Russia.1251    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## loaded via a namespace (and not attached):
##  [1] compiler_3.4.3  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
##  [5] tools_3.4.3     htmltools_0.3.6 yaml_2.1.16     Rcpp_0.12.15   
##  [9] stringi_1.1.7   rmarkdown_1.9   knitr_1.20      stringr_1.3.0  
## [13] digest_0.6.15   evaluate_0.10.1
```

**Comment by gforge** [comment]
Thanks for this excellent bug report. I've opened up the page in the browser and this seems to be a MathJax issue. Not sure how to turn it off though and if it belongs here. The $ sign isn't exotic enough to warrant htmlEntities, if you use `&#36;` it will work though as expected.

**Comment by gforge** [comment]
Added a 'str_replace_all` to the escape routine - could you  check if it works as expected? In the dev-branch.

**Comment by gdemin** [comment]
Thanks for quick reply. It works with `html.escape = TRUE` but don't work with `html.escape = FALSE`. Is it intentionally?

**Comment by gforge** [comment]
Yes, that is intentionally done. Otherwise the user won't be able to add MathJax in their tables.
