### ISSUE TITLE
Instalaltion Error on Ubuntu 16.04 while trying to install Hmisc

### ISSUE THREAD

**Issue by babycamel** [gforge/htmlTable#58]
htmlTable fails "unable to load shared object /stringi/libs/stringi.so : libicui18n.so.52  during lazy load. Any way to fix this?

Thanks.

**Comment by gforge** [comment]
This sounds like a stringi issue and not a htmlTable problem. There is probably a apt-get you need to do

**Comment by babycamel** [comment]
Reinstalling R and all libraries resolved it, it looked like memory for a
while but it wasn't.

Thanks


Research Website: rbeard.sdf.org
Github:  https://github.com/babycamel
Vitae: https://chroniclevitae.com/people/653618-rodney-beard
Orcid: http://orcid.org/0000-0001-5506-5424
Forum Fisheries Agency: http://ffa.int
Athabasca University:
https://business.athabascau.ca/faculty/rodney-beard-phd/
University of Glasgow:
https://www.gla.ac.uk/researchinstitutes/bahcm/staff/?action=person&id=4eddede28497
Translator's Cafe:  https://rmbeard.TranslatorsCafe.com
Translation: http://www.sprachspiegel.com
