### ISSUE TITLE
error with non-ANSI characters

### ISSUE THREAD

**Issue by mgacc0** [gforge/htmlTable#61]
I'm not sure if this only happens on Windows.
This is the result in Windows (with R 3.5.0 x64):
```r
htmlTable(data.frame(a="camión"))
```

a
--
1 | cami�n

The non-ANSI characters always get converted to strange symbols �.

**Comment by gforge** [comment]
This is not a htmlTable bug. This is an html issue with encoding

**Comment by mgacc0** [comment]
Could you offer some help with the diagnostics?
I suppose all Windows users are affected.

```r
str_native = "aeáé"
str_utf8 = enc2utf8(str)
Encoding(str_native)
# [1] "latin1"
Encoding(str_utf8)
# [1] "UTF-8"

Encoding(sprintf("%s</td>", str_native))
# [1] "unknown"
Encoding(sprintf("%s</td>", str_utf8))
# [1] "UTF-8"
```

And I have tried `htmlTable(str_utf8)` with no avail.

**Comment by gforge** [comment]
I don't see any ? in Ubuntu. This is not an htmlTable bug but something in your environment. The problem seems to be that your browser's character map can't handle the char.

**Comment by mgacc0** [comment]
Due to the html tag `content="text/html; charset=UTF-8"` the strings **should** be in UTF8 inside the html.
Since `htmlTable` doesn't force an explicit conversion, they get written in native OS encoding.
So, on Windows we obtain an html that contains some latin1 strings.

For example:
With `htmlTable("aeáé")`,

```html
<td style='border-top: 2px solid grey; border-bottom: 2px solid grey; text-align: center;'>aeáé</td>
```
On Windows, we obtain *61 65 E1 E9*  (the latin1 representation of *aeáé*)
but should be *61 65 C3 A1 C3 A9* (the UTF-8 representation of *aeáé*).

I think that `htmlTable` should do an explicit conversion (`enc2utf8`) to UTF-8 before `sprintf`.

**Comment by gforge** [comment]
I'm hesitant about autoconverting chars, if you want to use htmlTable in a document with a different charset, it could cause issues. I could possibly agree with you on the print.htmlTable to viewer when it has full control over the charset.

**Comment by lemna** [comment]
How about detecting the encoding of the string right before printing, then using that encoding in the header of the output to the viewer? That would only affect the viewer output and pick up the encoding used by the system. Something like this:
```r
  if (interactive() && !getOption("htmlTable.cat", FALSE) && 
      (is.function(useViewer) || useViewer != FALSE)) {
    if (is.null(args$file)) {
      args$file <- tempfile(fileext = ".html")
    }
    
    if(Encoding(x) == "latin1")
    {
      charset <- "ISO-8859-1"
    } else {
      charset <- Encoding(x)
    }
    header <- paste0("<meta http-equiv=\"Content-type\" content=\"text/html; charset=",
                    charset,
                    "\">")
    
    htmlPage <- paste("<html>", "<head>", header, 
                      "</head>", "<body>", "<div style=\"margin: 0 auto; display: table; margin-top: 1em;\">", 
                      x, "</div>", "</body>", "</html>", sep = "\n")
```
I tested this only in the viewer under windows 10, works as it should.

**Comment by mgacc0** [comment]
@lemna suggestion seems good.
Or, alternatively, as you have an `escape.html = FALSE` option, you could add another for this:
`forceUTF8encoding = FALSE` or `forceUTF8 = FALSE`.

**Comment by gforge** [comment]
Yeah, the `escape.html` opened a can of worms :grin: One of my strongest recollection when I was new to R was the overwhelming number of parameters. I still think this is a problem and since this is not a vital parameter it should probably not be added. If anything we could have another option available - this is probably how `escape.html` should have been handled from the gecko.

I don't think flexible encoding is a good option - another can of worms :snake: I have no clue of non-latin languages and supporting all seems like a nightmare. Is there a problem converting to UTF8 for all languages?

**Comment by mgacc0** [comment]
I think that forcing the encoding to be UTF-8 it's the best alternative.
Windows users will not need to use a different parameter when calling `htmlTable`.

And 99% of the people agree that the desired and most recommend encoding for an html file is UTF-8.

**Comment by gforge** [comment]
Not the biggest commit but the enc2utf8 should be enforced. I'll wait with pushing this onto CRAN as it seems a too trivial at the moment. Could you check if the dev-branch matches your expectations?
