### ISSUE TITLE
Write into documentation that compatibility with Excel is increased by using mso-number-format

### ISSUE THREAD

**Issue by rasmusrhl** [gforge/htmlTable#63]
If you style each cell with the CSS format "mso-number-format", then compatibility with Excel is increased. I did not know this before this SO-question. So maybe it is a good idea to put in the manual :) 

Use this css-matrix
`css_matrix <- matrix( data = "mso-number-format:\"\\@\"", nrow = nrow(df), ncol = ncol(df))
`

SO question:
https://stackoverflow.com/questions/48151491/convert-html-table-to-excel-using-vba

**Comment by gforge** [comment]
Excellent suggestion, do you mind doing a PR on this?
