### ISSUE TITLE
Export html tables to word automatically

### ISSUE THREAD

**Issue by elong0527** [gforge/htmlTable#65]
Is there a programming way to export many HTML tables into word?

It is nice to have the copy paste feature to word directly. However, people may get a request to repeatedly update some tables into word. I am wondering if there is a way to do it automatically.

**Comment by gforge** [comment]
Unfortunately the htmlTable package is directly outputting to html, I think there are other packages that may be better suited for this purpose, check out this post for instance https://rviews.rstudio.com/2017/10/04/wordr---a-new-r-package-for-rendering-documents-in-ms-word-format/
