### ISSUE TITLE
Large table html

### ISSUE THREAD

**Issue by ghost** [gforge/htmlTable#67]
I have a large dataframe which I want to make htmlTable of. Why is htmlTable so long compared to xtable. Following code takes only couple of seconds with xtable, while htmlTable takes about a minute to finish?

library(htmlTable)
library(xtable)
# A simple output
output <- matrix(1:62744,
                 ncol=44)
temp <- htmlTable(output) # couples of secends
tempXtable <- print(xtable::xtable(output), type="html") #takes about one minute, why ???

**Comment by gforge** [comment]
The htmlTable generates html output and not markdown. The table was never intended for large tables, its purpose is to produce tables for publication in journals.
