### ISSUE TITLE
How to print special characters

### ISSUE THREAD

**Issue by vonjd** [gforge/htmlTable#69]
```
> data.frame("äüöÄÖÜß")
  X.äüöÄÖÜß.
1    äüöÄÖÜß
```

The above works fine, the following does unfortunately not:

`htmlTable(data.frame("äüöÄÖÜß"))`

X.�������.
1	�������

What can I do? Thank you!

**Comment by gforge** [comment]
Special characters in html is governed by you UTF-8 setting and you probably have some bug there. The <?> can also be that your font doesn't have that specific character.
