### ISSUE TITLE
digits.nonzero argument to txtFmt: various problems

### ISSUE THREAD

**Issue by coolbaskin** [gforge/htmlTable#76]
https://github.com/gforge/htmlTable/blob/master/R/txtFrmt.R

line 246-248:

   if (digits.nonzero < digits) {
      stop("The digits.nonzero must be smaller than digits")
    }

Should be "must be larger than digits".

**Comment by coolbaskin** [comment]
Also, according to the logic in txtRound, **digits.nonzero** might be better called max_fractional_digits because it better reflects what it actually does according to code:  if rounding to **digits** after zero would not produce any non-zero digits, then round to the first significant digit after zero up to **digits.nonzero** digits after zero.

**Comment by coolbaskin** [comment]
Also this parameter causes errors when negative numbers are rounded:

`> txtRound(c(1.00234, 0.045, -1133.11), digits = 3, digits.nonzero = 5)

Error in if (decimal_position < -digits && decimal_position >= -digits.nonzero) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In (function (x, digits = 0, digits.nonzero = NA, txt.NA = "", dec = ".",  :
  NaNs produced`

**Comment by gforge** [comment]
Thanks fixed the negative number bug & error message in the `develop` branch.

Changing the parameter name is probably a bad idea as the package has a large audience. The docs could though easily be improved. I've added some explanation to the error message but it would be great if you could suggest something for the parameter description.
