### ISSUE TITLE
Auto add border styles to columns with grouped headers

### ISSUE THREAD

**Issue by martinschmelzer** [gforge/htmlTable#79]
I looked through the documentation but did not find an option that suits my needs.
When adding grouped headers using `cgroup` and `n.cgroup` I want to have borders to the left and right of those grouped columns.
I ended up extracting the raw HTML table code, parsing it using `xml2`, use the `n.cgroup` indices to identify the `td` elements to which I need to add the CSS border styles and return the modified HTML code into the htmlTable object.

did I miss anything or is this the only way to go?

**Comment by gforge** [comment]
Could you show the HTML-code, what you get together with a small PNG and then what you want and the CSS. Shouldn't bee too difficult to fix.

**Comment by martinschmelzer** [comment]
Well, I guess it should be possible to fix. Packages like `gt` or `flextable` have that additional flexibility. I switched from `gt` to htmlTable though, because sometimes I need stacked group headers ;)

Anyway, my workaround is too specific if you want to implement a solution on the package level. 
What would help me, but cover also every other "border case" I could think about is to have an argument, that allows me to set a left or right (or both) border to any column in `tbody`. The following picture shows what I need with goruped headers:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/7760212/91770061-cba4d380-ebe0-11ea-87a6-c1b5b377bf2e.png">

**Comment by gforge** [comment]
And the option of `align = "rr|rr|rrr|r"` doesn't give you the desired outcome?

**Comment by martinschmelzer** [comment]
Oops, I did not recognize that option. I will give it a try.

@gforge Man, How could I miss that? That is exactlywhat I needed. full control over where to set vertical rulers. Consider this closed... :)

**Comment by martinschmelzer** [comment]
The only thing thats not so pretty is the small space between the columns:

![grafik](https://user-images.githubusercontent.com/7760212/91811424-c0c55f80-ec2f-11ea-8ef1-cb9b68ab8575.png)

Is there a direct way to get rid of it? I know it is a result of those extra columns containing only a non breaking space.

**Comment by gforge** [comment]
Yeah, the empty column is there so that the header bottom border doesn't blend into one unit. I guess an option could be added for removing it but the question is if the result will be what you truly want. Another would be to use css.cell or add an argument similar to col.columns that takes not only color but also CSS-rules.

**Comment by martinschmelzer** [comment]
And how about adding an empty column on the right as well? :) I only would want a consistent layout: all vertical borders touch the group header bottom border or they dont (I prefer the latter)

**Comment by gforge** [comment]
I think I've fixed it in the feature/flexible_spacer_cells branch (checkout https://github.com/gforge/htmlTable/tree/). Do you mind testing it a bit before I push it to CRAN?

**Comment by martinschmelzer** [comment]
Awesome! I will make some tests today :)

**Comment by martinschmelzer** [comment]
@gforge The feature works nicely for me. `spacer.celltype = 'double_cell'` yields exactly what I was looking for. Thank you very much!

**Comment by gforge** [comment]
Great! I've been wanting to do this for a while but haven't really gotten around to it.

Do you have any input on the documentation and naming of the arguments? Will people understand "double_cell" - it's probably a bit technical...

**Comment by martinschmelzer** [comment]
Hm "double" might be enough as a valid value. In my eyes you described the use of `space.celltype` well enough. But I am in the matter now, may fresh eyes will find difficult.

**Comment by gforge** [comment]
Actually "double" should work as I use `match.arg()`. One thought I had was that maybe "center" or "split" would be more intuitive where you don't specify how the cells work
