### ISSUE TITLE
Conditional Formatting of Row or Column?

### ISSUE THREAD

**Issue by sco-lo-digital** [gforge/htmlTable#8]
Hi Max,

Wondering if htmlTable() can allow for conditional formatting of a row, column, or value? It seems from reading the vignettes this could be a possibility?

Scott

**Comment by gforge** [comment]
Yes, it is quite possible and already done - see Sergio Oller's [condformat](https://github.com/zeehio/condformat) on GitHub - try to convince him of publishing it on CRAN. All you need is to add a wrapper that generates the css.cell matrix according to the conditions. I also suggest that you have a closer look at http://renkun.me/formattable/ that does a very nice job at this.

**Comment by zeehio** [comment]
I will submit condformat to CRAN. I was waiting for you to upload htmlTable 1.4 and then I forgot to do it.

**Comment by gforge** [comment]
@zeehio - :+1:  great

**Comment by zeehio** [comment]
Just in case you are intereses, condformat is on CRAN:

https://cran.r-project.org/web/packages/condformat/index.html

https://cran.r-project.org/web/packages/condformat/README.html

@gforge, thanks for reminding me!

**Comment by gforge** [comment]
@zeehio - I'm glad that I remembered you and found our previous conversation.
