### ISSUE TITLE
Use `addHtmlTableStyle` inside a custom function and passing argument throws an error

### ISSUE THREAD

**Issue by martinschmelzer** [gforge/htmlTable#80]
Take the MWE:

```

library(htmlTable)

customTable <- function(x, css = c("custom-table", "custom-table-small")) {
  css.table <- match.arg(css)

  x <- addHtmlTableStyle(x, css.table = css.table)
  htmlTable(x)
}

customTable(x = mtcars)
```

I basically want to add different values for `css.table` . My real `customTable` is a little more complex. I get the error thet `css.table` cannot be found. I guess that this is a scoping issue. Is it intentional and what is the work-around besides adding the styles outside of my `customTable` function?

I am using the current developer branch `feature/flexible_spacer_cells`.

**Comment by gforge** [comment]
Thanks! That was certainly an evil bug :imp: as the argument had to be manually traversed through the environments. Should work now. It has been merged into develop. Please check that it works. I'll try to submit 2.1 to CRAN within a few days.

**Comment by martinschmelzer** [comment]
Oh yes that one was evil 👍 

When do you plan to release would have been my next question, great. I'll try it out....
