### ISSUE TITLE
Remove reshape dependency

### ISSUE THREAD

**Issue by MichaelChirico** [gforge/htmlTable#88]
{reshape} is an ancient package -- its successor, {reshape2}, is also now marked 'superseded'.

The package is only used for `reshape::cast()` here:

https://github.com/gforge/htmlTable/blob/82ffe152c9b59559686a8a7bb74c9121d9539cf3/vignettes/complex_tables.Rmd#L85-L87

It should be a drop-in replacement to use `reshape2::dcast()` instead, renaming argument `value` to `value.var`.

This could also be accomplished with `tidyr::pivot_wider()`, though I'm less familiar with the exact command to do so. This may be preferable since {tidyr} is already a Suggests dependency as well.

**Comment by gforge** [comment]
Thanks! I had completely forgotten about that. It is dropped from 2.4.2 that has just been submitted.
