### ISSUE TITLE
Re-group Non-adjacent Rows and Columns

### ISSUE THREAD

**Issue by ctmann** [gforge/htmlTable#9]
Package looks gorgeous! It's not clear how to group rows and columns that do not lie next to one another.

**Comment by gforge** [comment]
Thanks. Not entirely sure what in the documentation that isn't clear, have you looked at the [vignette](https://cran.r-project.org/web/packages/htmlTable/vignettes/general.html#row-groups)?

**Comment by ctmann** [comment]
My apologies. In the vignette... is it possible, for example, to define groups by putting '1st row, 5th row' in Group A? '2nd row, 3rd row, 4th row' in Group B, and '7th row and 8th row' in group C? Similarly with non-adjacent columns?

**Comment by gforge** [comment]
I can't quite envisage how that would look. I guess the easiest would be to have two cgroups with the same name, e.g. `cgroup = c("Group A", "Group B", "Group A", "", "Group C")` and `n.cgroup = c(1,3,1,1,2)`
